### ISSUE TITLE
Re-enable gas when they have better stability

### ISSUE THREAD

**Issue by endophage** [theupdateframework/notary#1030]
CI just spat out the following error, this is the second time we've had gas break CI

```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x6bb0e0, 0xc4200100a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/GoASTScanner/gas/rules.(*Credentials).matchGenDecl(0xc4201a6bd0, 0xc42015cd40, 0xc42006c1c0, 0xe1000000008745a0, 0x1, 0xc42006ac60)
	/go/src/github.com/GoASTScanner/gas/rules/hardcoded_credentials.go:62 +0x23e
github.com/GoASTScanner/gas/rules.(*Credentials).Match(0xc4201a6bd0, 0x85bea0, 0xc42015cd40, 0xc42006c1c0, 0x1, 0xc42006ac60, 0x8745a0)
	/go/src/github.com/GoASTScanner/gas/rules/hardcoded_credentials.go:34 +0x118
github.com/GoASTScanner/gas/core.(*Analyzer).Visit(0xc42006c1b0, 0x85bea0, 0xc42015cd40, 0x6bf180, 0x6cefa0)
	/go/src/github.com/GoASTScanner/gas/core/analyzer.go:214 +0x277
go/ast.Walk(0x85a7e0, 0xc42006c1b0, 0x85bea0, 0xc42015cd40)
	/usr/local/go/src/go/ast/walk.go:52 +0x63
go/ast.Walk(0x85a7e0, 0xc42006c1b0, 0x7efdc3aaced8, 0xc4200bfa20)
	/usr/local/go/src/go/ast/walk.go:186 +0x32bf
go/ast.walkStmtList(0x85a7e0, 0xc42006c1b0, 0xc42015d000, 0x3, 0x4)
	/usr/local/go/src/go/ast/walk.go:32 +0x89
go/ast.Walk(0x85a7e0, 0xc42006c1b0, 0x85bc20, 0xc4201a7bf0)
	/usr/local/go/src/go/ast/walk.go:224 +0x1d48
go/ast.Walk(0x85a7e0, 0xc42006c1b0, 0x7efdc3aa8250, 0xc4201a7c20)
	/usr/local/go/src/go/ast/walk.go:344 +0xf03
go/ast.walkDeclList(0x85a7e0, 0xc42006c1b0, 0xc420110d00, 0xc, 0x10)
	/usr/local/go/src/go/ast/walk.go:38 +0x89
go/ast.Walk(0x85a7e0, 0xc42006c1b0, 0x85be20, 0xc4200c2980)
	/usr/local/go/src/go/ast/walk.go:353 +0x29e4
github.com/GoASTScanner/gas/core.(*Analyzer).process(0xc42006c1b0, 0xc420218200, 0x39, 0x0, 0x0, 0xfd00000000000001, 0x8)
	/go/src/github.com/GoASTScanner/gas/core/analyzer.go:137 +0x5b7
github.com/GoASTScanner/gas/core.(*Analyzer).Process(0xc42006c1b0, 0xc420218200, 0x39, 0x3, 0x898201)
	/go/src/github.com/GoASTScanner/gas/core/analyzer.go:159 +0x55
main.main.func1(0xc420218200, 0x39, 0x85f5a0, 0xc4204e6270, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/HewlettPackard/gas/main.go:198 +0x15e
path/filepath.walk(0xc420218200, 0x39, 0x85f5a0, 0xc4204e6270, 0xc4201914e0, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:351 +0x81
path/filepath.walk(0xc4200f7410, 0x2b, 0x85f5a0, 0xc4204e61a0, 0xc4201914e0, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:376 +0x344
path/filepath.walk(0xc420016004, 0x20, 0x85f5a0, 0xc4201b04e0, 0xc4201914e0, 0x0, 0x1)
	/usr/local/go/src/path/filepath/path.go:376 +0x344
path/filepath.Walk(0xc420016004, 0x20, 0xc4201914e0, 0x0, 0xc4201a6b01)
	/usr/local/go/src/path/filepath/path.go:398 +0xd5
main.main()
	/go/src/github.com/HewlettPackard/gas/main.go:204 +0x12a5
```

**Comment by justincormack** [comment]
This issue can be closed now, it has been re-enabled for a while with no visible issues.
