### ISSUE TITLE
Panic With Token Auth Enabled

### ISSUE THREAD

**Issue by nathanjsweet** [theupdateframework/notary#1268]
I have got a working notary-server/signer set up, but when I turned token auth on I got the following panic:

I'm using notary-server 0.5.0.

```goroutine 100 [running]:
net/http.(*conn).serve.func1(0xc42000dd80)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xa45080, 0xc420010020)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/docker/notary/vendor/github.com/docker/distribution/context.getLogrusLogger(0x0, 0x0, 0xc4201a9998, 0x3, 0x3, 0x0)
	/go/src/github.com/docker/notary/vendor/github.com/docker/distribution/context/logger.go:86 +0x5d
github.com/docker/notary/vendor/github.com/docker/distribution/context.GetResponseLogger(0x0, 0x0, 0x8, 0xc420028800)
	/go/src/github.com/docker/notary/vendor/github.com/docker/distribution/context/http.go:176 +0x187
github.com/docker/notary/utils.(*rootHandler).ServeHTTP.func1(0xc4201a9b30)
	/go/src/github.com/docker/notary/utils/http.go:61 +0x3b
github.com/docker/notary/utils.(*rootHandler).ServeHTTP(0xc4202a9310, 0xe084e0, 0xc420185110, 0xc4200cbd10)
	/go/src/github.com/docker/notary/utils/http.go:69 +0x7c4
github.com/docker/notary/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202a9270, 0xe084e0, 0xc420185110, 0xc4200cbd10)
	/go/src/github.com/docker/notary/vendor/github.com/gorilla/mux/mux.go:98 +0x255
net/http.serverHandler.ServeHTTP(0xc420180f00, 0xe084e0, 0xc420185110, 0xc4200cbd10)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42000dd80, 0xe09360, 0xc420169140)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d```

**Comment by nathanjsweet** [comment]
Okay it looks like you guys fixed it here:
https://github.com/theupdateframework/notary/issues/1097

That being the case, do you think someone could push the images for 0.5.1 to the official docker hub repository?

**Comment by endophage** [comment]
Hi @nathanjsweet,

We're working on wrapping up a 0.6 in the immediate future. We're planning to get that out to the official images.

**Comment by endophage** [comment]
#1266 is specifically about creating a new release. Closing this as the original issue reported is already fixed and we have another issue tracking the release.
